name: Go-CI

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Set Up
        uses: actions/setup-go@v5
        with:
          go-version: ^1.20
        id: go

      - name: Check Out
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4.0.1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

  build:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Build
        run: go build ./...

  test:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Test
        run: go test ./... -v

  lint:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: Golangci-Lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout=30m
          version: latest
